### PR TITLE
NULL contextValue in RepositoryRetrieveProvider:retrieve

### PR DESCRIPTION
**Pull request by dkayiwa**
This pull request is for helping me find out why contextValue is always NULL in the RepositoryRetrieveProvider:retrieve() method callback.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @brynrhodes and team for the work on this. I confirm that after replacing ANCContactDataElements library with the one that you updated, i am able to see the PatientId coming through appropriately in the retrieve, with the expect contextValue.

But now the output careplan has changed from https://github.com/cqframework/clinical-reasoning/pull/268/commits/3a28c958dff7164b92ef739c58d6167016c913a2 to this: https://pastebin.com/Lf1jDRXn

I did not expect the output care plan to be different because i have not changed the data bundle. The only thing that changed in the ANCContactDataElements library.

**Comment by dkayiwa** [comment]
@c-schuler this is the pull request having the test to reproduce the `java.lang.IllegalArgumentException: Found multiple versions / instances of library FHIRHelpers.` error

**Comment by JPercival** [comment]
Did this get resolved for you?

**Comment by dkayiwa** [comment]
> Did this get resolved for you?

Yes it did.

**Pull request closed without merging**
